baseURL: "https://jongarrison.github.io"
languageCode: "en-us"
title: "Independent R&D"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main: #Menu Links "About Me" - "Photos" - etc
    - identifier: blog #JG - Reenable blog link when I have uptodate content
      name: Projects
      title: Projects
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Photography
      title: Photography
      url: https://www.flickr.com/photos/earthwandering/albums  #/gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jon Garrison"
  description: Public portfolio of Jon Garrison
  # staticPath: ""  # The path to serve the static files from
  # favicon: "/images/noun-led-7037426.png" #"/fav.png"
  favicon: "/images/noun-led-redfull-7037426.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jon Garrison" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, Im"
    title: "Jon"
    subtitle: "Can I help you make something?"
    content: "I'd like to be your R&D department. Software (front end/back end), firmware, electronics, 3D design, generative design, PCB design...  I'll try to share a little bit of everything here. If you'd like to talk about a project, feel free to reach out to me on [LinkedIn](https://www.linkedin.com/in/jonathangarrison/)"
    image: /images/ptwd250115/vases_code.png
    imageswitch:
      interval: 3000
      images:
        - image: "/images/red-zep.png"
        - image: "/images/splint/splint_on_model.png"
        - image: "/images/algorithmic-product-design/vent_animation.gif"
        - image: "/images/ptwd250115/vases_code.png"
        - image: "/images/ptwd250115/vases_gray.png"

    bottomImage:
      enable: false
      roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jongarrison
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jonathangarrison/
        - icon: fab fa-flickr
          url: https://www.flickr.com/photos/earthwandering
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/profile.png"
    content: |-
      I am a software engineer currently seeking projects. I have a fair amount of experience applying software to solve problems across a variety of domains. Need to develop an overheat warning system for a large boat engine? I can help. Want to build a machine that verifies a manufactured product is doing what it should? I can help. Do you want to tie your website directly to a back end manufacturing processes? I can help. The potential for software to make things more efficient, more functional, and more delightful is nearly limitless.
    skills:
      enable: true
      title: "Here are a few of the technologies I enjoy working with"
      items:
        - "Languages: Python, Javascript, C++, Java, SQL, HTML, CSS"
        - "Microcontroller Work: Arduino/C++/C, PlatformIO, Bluetooth, Nordic nRF52, esp32"
        - "3D and Generative Design: Rhino3D (with Grasshopper and Python), Fusion 360, OpenSCAD"
        - "Web Development: React, Node.js, Express, MongoDB, SQL, Bootstrap"
        - "Electronics: soldering, machine in the loop testing, debugging, PCB design, KiCad"
        - "Data Analysis: Python, Pandas, Numpy, Matplotlib, Seaborn, Jupyter Notebooks"
        - "Rapid prototyping: 3D printing, laser cutting, electronics design/assembly"
      


  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."


  # Education
  education:
    enable: false
    # title: "Custom Name"
    # index: false
    # items:
    #   - title: "Master of Business Administration"
    #     school:
    #       name: "University of California, Berkeley"
    #       url: "https://example.org"
    #     date: "2013 - 2015"
    #     GPA: "3.8 out of 5.0"
    #     content: |-
    #       Extracurricular Activities
    #         - Lorem ipsum dolor sit amet consectetur adipisicing elit.
    #         - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      # - title: Google kickstart runner
      #   content: I solved all problems with optimal solution.
      #   url: https://example.com
      #   image: /images/achievment.jpg

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: "LED Lighting"
        content: I've worked on a variety of LED lighting projects, custom 3D printed LED matrix displays, art pieces, and product prototypes.
        image: /images/led_grid_square.gif
      # - title: Hugo Profile
      #   content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile.png
      #   featured:
      #     name: Demo
      #     link: https://hugo-profile.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fa fa-envelope
      #       url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/hugo-profile

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:gurusabarisha@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 10
      title: Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/jongarrison
      linkedin: https://linkedin.com/in/jonathangarrison
      flickr: https://www.flickr.com/photos/earthwandering
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: false
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: " "
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
